# Change these first
owner: nautical-commerce # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Website (www.nauticalcommerce.com)
    url: https://www.nauticalcommerce.com
  - name: Nautical Guide (guide.nauticalcommerce.com)
    url: https://guide.nauticalcommerce.com
  - name: Hosted Checkout
    url: https://checkout.nauticalcommerce.com/version
  - name: Data Ingestion API
    url: https://ingestion-api.mpconsole.com/
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nauticalcommerce.com
  # baseUrl: /statuspage
  logoUrl: https://avatars.githubusercontent.com/u/63327933
  name: Nautical Commerce
  # introTitle: "**Your** marketplace operating system."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Website ↗
      href: https://www.nauticalcommerce.com
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
